import './globals.css'
import './styles/fonts.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Sidebar from "../components/Sidebar"
import CustomCursor from "../components/Cursor";
import Home from '@/app/home/page';
import About from '@/app/about/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <body className={inter.className}>
    <CustomCursor />
    <main className="flex flex-row">
        { children }
    </main>
  </body>
  )
}
